# Generated by Django 6.0.2 on 2026-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='CategoryName'),
        ),
    ]
